### ISSUE TITLE
Part 2 - Route params

### ISSUE THREAD

**Issue by luis-carlos** [ember-learn/super-rentals-tutorial#179]
Hi all,

After following instructions on how to fix the error reported on thi section, test remains without passing

https://guides.emberjs.com/release/tutorial/part-2/route-params/#toc_component-tests-with-access-to-the-router

I even copied file tests/integration/components/rental-test.js from this repo and the problem persists

![image](https://user-images.githubusercontent.com/4765387/108592694-b52c3900-7334-11eb-91c7-1cdb8650d22d.png)

Are the instructions on the tutorial complete?

**Comment by ijlee2** [comment]
@chancancode @xg-wang Could you confirm when this issue can be closed? I believe there was an update to the Super Rentals Tutorial recently, but don't think it's live yet (not available till 3.26 release, perhaps)?

**Comment by chancancode** [comment]
I believe it is fixed now, but apps would need to upgrade to latest patch release of ember-source to pull in the bug fix. There is an update to the text (to remove some setup that is no longer necessary), which I still need to merge into guides-source, but that would just be redundant boilerplate and shouldn’t break things as far as I know. @xg-wang cqn confirm

**Comment by xg-wang** [comment]
@ijlee2 the fixes have been released for 3.24.3 and 3.25.3, can you try bump your repro app to 3.25.3?
https://github.com/emberjs/ember.js/issues/19408#issuecomment-792432681

**Comment by ijlee2** [comment]
Thank you both for a quick response. Yep, I verified that, by updating `ember-source` in my repro app to `3.25.3`, the failing test passes again!

I will close this issue.

**Comment by shekinahsmith** [comment]
@ijlee2 I'm running into this issue still. I just updated the tutorial app and this test won't pass even with the addition of

```
  hooks.beforeEach(function () {
    this.owner.setupRouter();
  });
```

**Comment by chancancode** [comment]
@shekinahsmith Can you push your commits somewhere?
